name: Windows Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset windows-x64

      - name: Build
        run: cmake --build --preset windows-x64

      - name: Package plugin
        run: cmake --install build_x64 --config RelWithDebInfo --prefix package

      - name: Upload Windows plugin
        uses: actions/upload-artifact@v4
        with:
          name: Clatasha-HUD-Windows-x64
          path: package/
          if-no-files-found: error
